services:
  livepeer-orchestrator:
    image: livepeer/go-livepeer:latest
    container_name: livepeer-orchestrator
    runtime: nvidia
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - vtuber_network
    ports:
      - 9995:9995
      - 127.0.0.1:7935:7935
    volumes:
      - vtuber_orch_data:/root/.lpData
      - livepeer_models:/models
      - ./config/keystore:/root/.lpData/keystore:ro
      - ./config/vtuber.conf:/root/.lpData/vtuber.conf:ro
      - ./config/ethpass:/root/.lpData/.ethpass:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: [-config, /root/.lpData/vtuber.conf]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  vtuber_network:
    external: true
    name: vtuber_network

volumes:
  vtuber_orch_data:
  livepeer_models:
