services:
  ollama:
    image: ollama/ollama:latest
    container_name: vtuber-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    networks:
      - scb_bridge_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Fallback for systems without GPU
    profiles:
      - gpu

  ollama-cpu:
    image: ollama/ollama:latest
    container_name: vtuber-ollama-cpu
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    networks:
      - scb_bridge_net
    profiles:
      - cpu

networks:
  scb_bridge_net:
    external: true
    name: docker-vt_scb_bridge_net

