# docker-compose.yml
services:
  nginx-rtmp:
    build: ./docker/rtmp
    # image: alfg/nginx-rtmp:latest   # Replaced with build context
    # command: ["nginx", "-c", "/etc/nginx/nginx.conf"] # Command is now in Dockerfile
    ports:
      - "1935:1935"                 # RTMP
      - "8080:8080"                 # HLS/monitor page
    volumes:
      - ./docker/rtmp/nginx.conf:/etc/nginx/nginx.conf