x-common: &common-config
  restart: always
  logging:
    driver: 'json-file'
    options:
      max-size: '100m'
      max-file: '5'

services:
  eliza:
    image: phalanetwork/eliza:v0.1.6-alpha.4
    container_name: eliza
    stdin_open: true
    tty: true
    environment:
      - REDPILL_API_KEY=${REDPILL_API_KEY}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
      - DISCORD_API_TOKEN=${DISCORD_API_TOKEN}

  nginx:
    image: phalanetwork/docker-log-api
    <<: *common-config
    container_name: logs
    ports:
      - '8080:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mkswap

  mkswap:
    image: busybox
    privileged: true
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        if ! [ -f /host/swap0 ]; then
          fallocate -l 4G /host/swap0 &&
          chmod 600 /host/swap0 &&
          mkswap /host/swap0 &&
          swapon /host/swap0
        fi
        echo 30 > /host/proc/sys/vm/swappiness
    volumes:
      - /:/host
    restart: 'no'
