version: '3.8'

services:
  rtmp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtmp-voice-server
    ports:
      - "1935:1935"  # RTMP streaming port
      - "8080:8080"  # HTTP/HLS/Statistics port
    volumes:
      # Persistent storage for recordings
      - ./recordings:/var/recordings
      # Optional: Custom nginx config override
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - RTMP_MAX_STREAMS=1024
    restart: unless-stopped
    healthcheck:
      test: ["/usr/local/bin/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

# Optional: If you want to use external volumes
volumes:
  rtmp_recordings:
    driver: local

# Network configuration (optional)
networks:
  default:
    name: rtmp-network 