#!/bin/bash

echo "🚀 GraphFlow Monitoring Setup"
echo "============================"
echo ""
echo "📊 Grafana Access:"
echo "  URL: http://localhost:3001"
echo "  Username: admin"
echo "  Password: admin"
echo ""
echo "📈 Prometheus Access:"
echo "  URL: http://localhost:9091"
echo "  Targets: http://localhost:9091/targets"
echo ""
echo "✅ Current Status:"
echo ""

# Check if services are running
echo -n "  Grafana: "
curl -s -o /dev/null -w "%{http_code}" http://localhost:3001/api/health | grep -q "200" && echo "✓ Running" || echo "✗ Not running"

echo -n "  Prometheus: "
curl -s -o /dev/null -w "%{http_code}" http://localhost:9091/-/healthy | grep -q "200" && echo "✓ Running" || echo "✗ Not running"

echo -n "  GraphFlow Metrics: "
curl -s -o /dev/null -w "%{http_code}" http://localhost:8081/metrics | grep -q "200" && echo "✓ Available" || echo "✗ Not available"

echo ""
echo "📋 Quick Setup Steps:"
echo ""
echo "1. Open Grafana in your browser:"
echo "   xdg-open http://localhost:3001 || open http://localhost:3001"
echo ""
echo "2. Login with admin/admin"
echo ""
echo "3. Add Prometheus Data Source:"
echo "   - Go to Configuration (⚙️) → Data Sources"
echo "   - Click 'Add data source'"
echo "   - Select 'Prometheus'"
echo "   - Set URL to: http://prometheus:9090"
echo "   - Click 'Save & Test'"
echo ""
echo "4. Import the Dashboard:"
echo "   - Go to Create (+) → Import"
echo "   - Upload: monitoring/grafana/dashboards/graphflow-dashboard.json"
echo "   - Select the Prometheus data source"
echo "   - Click 'Import'"
echo ""
echo "📊 Available Metrics:"
echo ""
curl -s http://localhost:8081/metrics | grep "^# HELP graphflow" | head -10
echo ""
echo "For detailed instructions, see: monitoring/MONITORING_SETUP.md"