name: Build and Push Docker Images

on:
  push:
    branches: [main, master]
    tags:
      - 'v*.*.*' # Trigger on version tags
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }} # This is good for a single image repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # For OIDC if you use keyless signing

    strategy:
      matrix:
        include:
          - service: neurobridge
            dockerfile: ./NeuroBridge/dockerfile
            context: ./NeuroBridge
            image_suffix: neurobridge
          - service: webapp
            dockerfile: ./webapp/Dockerfile # Assuming Dockerfile path
            context: ./webapp
            image_suffix: webapp
          - service: neurosync-worker
            dockerfile: ./NeuroBridge/dockerfile # This points to the same Dockerfile as neurobridge
            context: .                            # Context is repo root
            image_suffix: neurosync-worker
          # Add other services here
          # - service: autonomous-starter
          #   dockerfile: ./autonomous-starter/Dockerfile
          #   context: ./autonomous-starter
          #   image_suffix: autonomous-starter

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image_suffix }}
          # github.repository_owner is generally preferred for organization-level packages
          # For personal repos, github.repository can be used as <owner>/<repo_name>/<image_suffix>

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }} # Don't push on PRs
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # platforms: linux/amd64,linux/arm64 # Uncomment for multi-arch builds 